# Ref: https://wanago.io/2023/01/16/api-nestjs-docker-compose/

version: '3.8'

services:
  database:
    image: postgres:13-alpine
    restart: always
    networks:
      - postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=for_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
  
  # enable only when target image exists
  # nest_api:
  #     image: nest_api
  #     env_file:
  #       - .env
  #     ports:
  #       - "3000:3000"
  #     depends_on:
  #       - database
  #     networks:
  #       - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge