# Ref: https://wanago.io/2023/01/16/api-nestjs-docker-compose/

version: '3.8'

services:
  database:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=for_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    
  redis:
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"
  
  # enable only when target image exists
  service:
    image: nest_api:v1
    restart: always
    environment:
      - DB_HOST=database
      - QUEUE_HOST=redis
    ports:
      - "80:3030" 
    depends_on:
      - database
      - redis
  
volumes:
  postgres_data:
